name: Build check on push
on:
  push:
    branches-ignore:
      - main
      - devops
jobs:
  call-reusable-workflow:
    uses: spring-bot-test/demospringboot/.github/workflows/reusable-workflow.yml@main
    with:
      branch_name: ${{ github.ref_name }}
      build_with_tests: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # build-and-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Set up JDK 18
  #     uses: actions/setup-java@v3
  #     with:
  #       distribution: 'temurin'  # Options: 'temurin', 'zulu', 'adopt', 'oracle', etc.
  #       java-version: '18'

  #   - name: Cache Maven packages
  #     uses: actions/cache@v3
  #     with:
  #       path: ~/.m2/repository
  #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
  #       restore-keys: ${{ runner.os }}-maven-
    
  #   - name: Build and check
  #     run: mvn clean package