name: Building docker image and pushing to ACR
on:
    push:
    pull_request:
      branches:
        - main
        - devops
jobs:
    Build-and-Test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v3
            - name: setup java version to 18
              uses: actions/setup-java@v3
              with:
                java-version: '18'
                distribution: 'temurin'

    Creating-and-pushing-image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Extract application version from pom.xml
              run: |
                version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                echo "version=$version" >> $GITHUB_ENV
                artifactid=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
                echo "artifactId=$artifactId" >> $GITHUB_ENV
            - name: building docker image
              run: |
                echo "Building image with version ${{ env.version }} and repository_name - ${{ env.artifactId }}"
            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v2
          
            # - name: Log in to Azure Container Registry
            #   run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          
            # - name: Build and push Docker image
            #   run: |
            #     docker build -t ${{ secrets.ACR_NAME }}/my-app:${{ env.version }} .
            #     docker push ${{ secrets.ACR_NAME }}/my-app:${{ env.version }}
          
            # - name: Log out from Azure Container Registry
            #   run: docker logout ${{ secrets.ACR_NAME }}