name: Testing and Generating the Report

on:
  pull_request:
    branches-ignore: 
      - main
      - devops

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build Maven project
      run: mvn clean install -DskipTests

    - name: Run tests with Maven
      run: mvn test

    - name: Generate Surefire Report
      run: mvn surefire-report:report-only

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/site/surefire-report.html