name: Building docker image and pushing to ACR on pull request

on:
  pull_request:
    branches:
      - main
      - devops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Build Maven project
      run: mvn clean install -DskipTests

    - name: Extract application version and artifactId from pom.xml
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$version" >> $GITHUB_ENV
        artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
        echo "artifactId=$artifactId" >> $GITHUB_ENV

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Log in to Azure Container Registry
    #   run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    # - name: Build and push Docker image
    #   run: |
    #     docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.artifactId }}:${{ env.version }} .
    #     docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.artifactId }}:${{ env.version }}

    # - name: Log out from Azure Container Registry
    #   run: docker logout ${{ secrets.ACR_NAME }}.azurecr.io
