name: my push workflow
on:
    push
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: echo "Hello Welcome to spring boot application"
            - name: checkout
              uses: actions/checkout@v3
            - name: Extract version from pom.xml
              run: |
                version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                echo "version=$version" >> $GITHUB_ENV
        
            - name: Build Docker image
              run: echo "building image ${{ env.version }}"
            - name: building docker image
              run: |
                echo "Building image with version ${{ env.version }}"
                docker build -t my_springboot .
                az version