name: my push workflow
on:
  push:
    branches-ignore: 
      - main
      - devops
      - feature1
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: echo "Hello Welcome to spring boot application"
            - name: checkout
              uses: actions/checkout@v3
            - name: Extract version from pom.xml
              run: |
                version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
                echo "version=$version" >> $GITHUB_ENV
            - name: building docker image
              run: |
                echo "Building image with version ${{ env.version }}"
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
          
            - name: Log in to Azure Container Registry
              run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          
            - name: Build and push Docker image
              run: |
                docker build -t ${{ secrets.ACR_NAME }}/my-app:${{ env.version }} .
                docker push ${{ secrets.ACR_NAME }}/my-app:${{ env.version }}
          
            - name: Log out from Azure Container Registry
              run: docker logout ${{ secrets.ACR_NAME }}