name: Reusable Workflow

on:
  workflow_call:
    inputs:
      branch_name:
        description: 'Branch name'
        required: true
        type: string
      build_with_tests:
        description: 'Run tests with the build'
        required: false
        default: true
        type: boolean
    secrets:
      GITHUB_TOKEN1:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'

    - name: Cache Maven packages package
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build Maven project
      run: mvn clean install -DskipTests

    - name: Run tests with Maven
      if: ${{ inputs.build_with_tests }}
      run: mvn test

    - name: Generate Surefire Report
      run: mvn surefire-report:report-only

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/site/surefire-report.html
