name: CI
on: workflow_dispatch #[push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Send notification to Teams
      if: always() # Ensure this step runs regardless of success or failure
      run: |
        STATUS=${{ job.status }}
        if [ "$STATUS" == "success" ]; then
          COLOR="00FF00"
          MESSAGE="Build succeeded!"
        else
          COLOR="FF0000"
          MESSAGE="Build failed!"
        fi
        curl -H 'Content-Type: application/json' -d '{
          "title": "GitHub Actions CI",
          "text": "The build on branch `${{ github.ref }}` has completed.",
          "themeColor": "'$COLOR'",
          "sections": [{
            "activityTitle": "**Job Status**",
            "activitySubtitle": "'"$MESSAGE"'",
            "facts": [
              {
                "name": "Repository",
                "value": "'${{ github.repository }}'"
              },
              {
                "name": "Commit",
                "value": "'${{ github.sha }}'"
              },
              {
                "name": "Ref",
                "value": "'${{ github.ref }}'"
              }
            ]
          }]
        }' 
## ${{ secrets.TEAMS_WEBHOOK_URL }}
