name: test

on:
  push:
    branches:
      - main
      - feature1

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout feature1 branch
        run: |
          git checkout feature1

      - name: Modify pom.xml version
        run: |
          # Example command to modify the version, adjust as needed
          sed -i 's/<version>.*<\/version>/<version>1.1.1<\/version>/g' pom.xml

      - name: Commit and push changes
        run: |
          git add pom.xml
          git commit -m "Update version in pom.xml"
          git push origin feature1
